#!/usr/bin/env ruby

require 'timing_method'

# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100, and 2 <= b <= 100?

timing_method do

  limit = 100

  terms = Array.new

  (2..limit).each{|a|
    (2..limit).each{|b|
      terms << a**b
    }
  }

  puts "There are #{terms.uniq.size} distinct terms in the sequence a^b for 2 <= a <= #{limit} and 2 <= b <= #{limit}."

end
