#!/usr/bin/env ruby -wKU

require "timing_method"

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n-1)   1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

class Integer
  def makeTriangle
    self * (self + 1) / 2
  end

  def makePentagonal
    self * (3*self - 1) / 2
  end

  def makeHexagonal
    self * (2*self - 1)
  end
end

timing_method do

  i = 144

  pent, hex = [], [], []

  while i < 35_000
    # tri << i.makeTriangle
    pent << i.makePentagonal
    hex << i.makeHexagonal
    i += 1
  end

  # Every hexagonal number is also a triangular number.
  # n = (tri & pent & hex).select{|x| x > 40755}[0] # Abusing array intersections
  n = (pent & hex)[0] # Abusing array intersections

  puts "The next number after 40755 that is a triangle, pentagonal, and hexagonal number is #{n}."

end
